language: rust

rust:
  - stable

install:
  - wget https://github.com/FactomProject/distribution/releases/download/v6.5.0/factom-amd64.deb
  - sudo dpkg -i factom-amd64.deb

script:
  - factomd -network=LOCAL -blktime=20 &
  - factom-walletd &
  - sleep 15
  - factom-cli importaddress Fs3E9gV6DXsYzf7Fqx1fVBQPQXV695eP3k5XbmHEZVRLkMdD9qCK
  - factom-cli importaddress Es3LS7zYa9DSzZuUC14HDpMinehmzz61JG1XFY62rX5pVDenH8Pk
  - factom-cli buyec FA2jK2HcLnRdS94dEcU27rF3meoJfpUcZPSinpb7AwQvPRY6RL1Q EC2MJzCcHqYJyujnPzjitEaHhtEPVBhmEWUKkv4SVaaKeYcq3fqK 10000
  - cargo test

matrix:
  fast_finish: true
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
