language: rust
rust:
  - stable
matrix:
  fast_finish: true
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: stable
  - env: TARGET=x86_64-pc-windows-msvc
    rust: stable
  - env: TARGET=x86_64-apple-darwin
    rust: stable
  - env: TARGET=x86_64-unknown-freebsd
    rust: stable
  - env: TARGET=aarch64-linux-android
    rust: stable
  - env: TARGET=armv7-unknown-linux-gnueabihf
    rust: stable
  - env: TARGET=powerpc-unknown-linux-gnu
    rust: stable